apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-get-tasks-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-get-tasks-api
  template:
    metadata:
      labels:
        app: todo-get-tasks-api
    spec:
      containers:
      - name: todo-get-tasks-api
        image: todoappacr001.azurecr.io/todo-get-tasks-api:v1
        ports:
        - containerPort: 8000
        env:
          - name: CONNECTION_STRING
            value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:todoapp-sql-server01.database.windows.net,1433;Database=sql-database-todoapp;Uid=devdbprivilgeuser;Pwd={your_password_here};Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"                                          


