apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-get-task-api-ingress
spec:
  ingressClassName: ingress-nginx-controller
  rules:
    - host: get-tasks-api.applicationtesting.online
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: todo-get-task-api
                port:
                  number: 80
